### PR TITLE
use Clang format to enforce code style

### PR DESCRIPTION
**Pull request by alex19EP**
note: this requires #30  and #31 

I tried to keep the general style of the code.
and at the same time improved the readability, at least so it seems to me.

### CODE REVIEW

**Comment by williamh** [comment]
Please stick with K&R style with tabs for indentation. I find multiple spaces per indent level very hard to work with.

**Comment by williamh** [comment]
Also, I ask that you not delete .indent.pro in this pr, we can do that once we make sure klang-format produces the same formatting this .indent.pro does.

**Comment by alex19EP** [comment]
> Please stick with K&R style with tabs for indentation. I find multiple spaces per indent level very hard to work with.

I don't quite understand. now tab is used for indentation, and spaces are used only for code alignment.

I would like to leave spaces for alignment, as they make it easier to read code on the braille display.

> Also, I ask that you not delete .indent.pro in this pr, we can do that once we make sure klang-format produces the same formatting this .indent.pro does.

ok. will bring it back.

**Comment by williamh** [comment]
I would not make any manual changes in the same commit where the formatter makes changes. For example, I see espeak being changed to espeak-ng several times in this commit. If you combine your own changes with changes the formatter made, it is not possible to tell which ones are which.

**Comment by alex19EP** [comment]
> I would not make any manual changes in the same commit where the formatter makes changes. For example, I see espeak being changed to espeak-ng several times in this commit. If you combine your own changes with changes the formatter made, it is not possible to tell which ones are which.

oh sorry didn’t think about it at all. fixed.

**Pull request merged**
